### ISSUE TITLE
Use TypeScript

### ISSUE THREAD

**Issue by daviddao** [cytoai/cyto#11]
Maybe not relevant yet but thinking about open sourcing and encouraging more external developers, we could imagine on moving to TypeScript for more type safety (like deployed in tensorflow.js)

It could also help us get moving towards continuous integration and deployment.

**Comment by 0x00b1** [comment]
@daviddao I like you and I like TypeScript, but you should contribute before suggesting we rewrite the application in a different programming language! 😆 😗

**Comment by daviddao** [comment]
We don't have to rewrite everything as it's dynamic typing :) - just the part which we want to open up for contributors!
