### ISSUE TITLE
Users should be able to open a Lightbox-like view of an image

### ISSUE THREAD

**Issue by 0x00b1** [cytoai/cyto#41]
This view will provide the screen real estate needed to expose image viewing (e.g. hiding and showing channels) and image editing (e.g. rescaling intensities) features to the user.

**Comment by 0x00b1** [comment]
We have `onClick` implemented for one image but it presently doesn’t do anything. Maybe we should use this event and state for opening the Lightbox-like view (i.e. clicking an image pops the view)?

**Comment by AlexChrisF** [comment]
Good idea!

**Comment by AlexChrisF** [comment]
Done
