### ISSUE TITLE
The Gallery component’s onmousemove event is always listening (and updating the entire app on every movement)

### ISSUE THREAD

**Issue by 0x00b1** [cytoai/cyto#58]
We should only listen to onmousemove after a user has clicked (ideally inside the Gallery component).

**Comment by AlexChrisF** [comment]
Fixed in  commit c6f751417c7bc39246ae8011f96f5d11f8dacc39

**Comment by AlexChrisF** [comment]
Listeners still active

**Comment by AlexChrisF** [comment]
Fixed
