### ISSUE TITLE
Opening a sample when a sample is open does not open the new sample

### ISSUE THREAD

**Issue by 0x00b1** [cytoai/cyto#73]
Steps to reproduce

1. Open a sample, e.g. MNIST
2. Open a new sample, e.g. CIFAR-10

The CIFAR-10 sample does not open.

**Comment by AlexChrisF** [comment]
Seems to work, what's your browser?

**Comment by AlexChrisF** [comment]
Fixed: Clicking on the sample avatar was only closing the window and not loading the sample
